on:
  push:
    branches:
      - master

env:
  SemVer: 0.1.0
  Project: GithubActionPinner
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81 # pin@v2 
    - uses: actions/setup-dotnet@b7821147f564527086410e8edd122d89b4b9602f # pin@v1 
      with:
        dotnet-version: 3.1.100
    - run: echo "::set-env name=Version::${{ env.SemVer }}.${{ GITHUB.RUN_NUMBER }}"
    - run: dotnet build -c Release
    - run: dotnet test --no-build -c Release
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dotnet publish --no-build -c Release ${{ env.Project }}/${{ env.Project }}.csproj -o release/${{ env.Project }} /p:Version=${{ env.Version }}
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1 
      with:
        name: ${{ matrix.os }}
        path: release/${{ env.Project }}
