on:
  push:
    branches:
      - master

env:
  SemVer: 1.0.1
  Project: GithubActionPinner
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2 
    - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439 # pin@v1 
    - run: echo "Version=${{ env.SemVer }}.${{ GITHUB.RUN_NUMBER }}" >> ${{ env.GITHUB_ENV }}
    - run: dotnet build -c Release
    - run: dotnet test --no-build -c Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dotnet publish --no-build -c Release ${{ env.Project }}/${{ env.Project }}.csproj -o release/${{ env.Project }} /p:Version=${{ env.Version }}
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1 
      with:
        name: ${{ matrix.os }}
        path: release/${{ env.Project }}
